# Generated by Django 5.1.3 on 2025-01-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterfAz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='ai',
            field=models.CharField(choices=[('SC', 'StarCoder'), ('OL', 'Ollama'), ('OA', 'OpenAI'), ('AI', 'Unknown')], default='AI', max_length=2),
        ),
    ]
