name: Validate Commit Messages

on:
  push:
    branches:
      - '**'  

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Validate Commit Messages
        run: |
          git log --oneline FETCH_HEAD | while read -r commit; do
            # Extracting the message ignoring the hash
            message=$(echo "$commit" | sed 's/^[a-f0-9]* //')
            
            # Excluding fusion's commit
            if [[ "$message" =~ ^Merge ]]; then
              continue
            fi

            # Validating the message
            if [[ ! "$message" =~ ^(feat:|fix:|doc:)[[:space:]]+[A-Z] ]]; then
              echo "❌ Invalid commit message: $message"
              echo "Expected format: feat/fix/doc: \"Message\", where Message starts with an uppercase letter."
              exit 1
            fi
          done